title: Amy Chamberlain # your name (or website title) here
<img src="https://github.com/AmyJoCN/amyjocn.github.io/blob/master/images/Logo.png" width="100" height="100"> # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  //Data Explorer// 
  <br><br>
  Recent graduate of University of WA - Certificate in Data Analytics program covering data analysis and machine learning using R and SQL, and data visualization using Power BI and Excel. My experience includes a diversity of roles/responsibilities from applied marketing research and survey/test design to candidate screening, in organizations ranging from academia to corporate tech. Pattern-finding and organizing, exploring, and analyzing information to meet customer criteria has always been central to my work history and education. 
  <br><br>
  <a href="https://www.linkedin.com/in/amyjocn/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
