title: Amy Chamberlain # your name (or website title) here
logo: "/images/Logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br>
  //Data Explorer// 
  <br><br>
  Recent graduate of University of WA - Certificate in Data Analytics program covering data analysis and machine learning using R and SQL, and data visualization using Power BI and Excel. 
  <br><br>
  <a href="https://www.linkedin.com/in/amyjocn/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
